return {}
-- return {
--   {
--     "nvim-neo-tree/neo-tree.nvim",
--     branch = "v3.x",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
--       "MunifTanjim/nui.nvim",
--       "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
--     },
--     config = function()
--       require("neo-tree").setup({
--         -- window = { position = "" },
--         -- mappings = {},
--         -- source_selector = { tabs_min_width = 2, tabs_max_width = 2 },
--       })
--     end,
--   },
-- }
